In [1]:
import numpy as np

In [25]:
A = np.arange(10).reshape(2,5)

In [26]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
A.sum()

np.int64(45)

In [12]:
A.rowsum()

AttributeError: 'numpy.ndarray' object has no attribute 'rowsum'

In [13]:
B = A + 5

In [14]:
B

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
B = A * 1000

In [28]:
B

array([[   0, 1000, 2000, 3000, 4000],
       [5000, 6000, 7000, 8000, 9000]])

In [29]:
B = A // 10

In [18]:
b

NameError: name 'b' is not defined

In [31]:
B

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
list1 = [1,2,3,"YU", 0]

In [38]:
S = np.array(list1)

In [40]:
np.argmax(S)

np.int64(3)