In [1]:
# 행렬이나 대규모 다차원 배열을 쉽게 처리할 수 있는 자료구조 긴으을 지원하며, 다양한 수치해석과 통계분석 긴으을 제공하는 파이썬 라이브러리



In [3]:
import numpy as np

In [8]:
a = np.arange(10).reshape(2,5)

In [9]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
a.ndim

2

In [21]:
a.shape

(2, 5)

In [22]:
a.size

10

In [23]:
a.dtype

dtype('int64')

In [24]:
a.itemsize

8

In [25]:
a.data

In [26]:
id(a)

4453497232

In [28]:
A = np.array([[1,2,3],[4,5,6]], dtype=np.int32)

In [29]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
A

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [41]:
B = np.zeros((5,3,3), order="C")

In [42]:

B

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [45]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])