In [1]:
import numpy as np

In [2]:
A = np.arange(3)

In [3]:
A

array([0, 1, 2])

In [4]:
print(A)

[0 1 2]


In [7]:
print(A.dtype)


int64


In [11]:
B = np.arange(3.0)

In [12]:
B.dtype

dtype('float64')

In [13]:
A = np.empty([2,3])

In [14]:
A

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
B = np.zeros(5)

In [17]:
B

array([0., 0., 0., 0., 0.])

In [18]:
C = np.ones(5)

In [22]:
C

array([1., 1., 1., 1., 1.])

In [23]:
D = np.full([2,3],5)

In [24]:
D

array([[5, 5, 5],
       [5, 5, 5]])

In [25]:
I = np.identity(3)

In [26]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
F = np.eye(5)

In [28]:
F

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
l = [1,2,3,3.14]

In [30]:
### 파이썬 리스트 와 ndarray 비교

In [31]:
l = [1,2,3,3.14,'YU']

In [33]:
type(l)

list

In [34]:
type(l[3])

float

In [36]:
type(l[4]) # 어떤 종류의 타입이던 하나로 묶어서 사용할 수 있다

str

In [37]:
a = np.array([1,2,3,4,5])

In [38]:
a

array([1, 2, 3, 4, 5])

In [39]:
type(a)

numpy.ndarray

In [40]:
print(a)

[1 2 3 4 5]


In [43]:
print(l) # 리스트는 구분자 사용

[1, 2, 3, 3.14, 'YU']


In [47]:
a.dtype

dtype('int64')

In [ ]:
b = np.array(l) # 전부 문자열로 통합된 모습

In [49]:
b

array(['1', '2', '3', '3.14', 'YU'], dtype='<U32')

In [50]:
print(l)

[1, 2, 3, 3.14, 'YU']


In [51]:
type(b[0])

numpy.str_

In [52]:
l[0] + 10

11

In [54]:
b[0] + '10'

'110'

In [55]:
int(b[0]) + 10

11

In [56]:
a.shape 

(5,)

In [57]:
a.ndim

1

In [58]:
a.dtype

dtype('int64')

In [59]:
a.itemsize

8

In [60]:
c = np.ones_like(a)

In [61]:
c

array([1, 1, 1, 1, 1])

In [62]:
c.shape

(5,)