In [2]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,-1)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [6]:
a[::-1,::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [7]:
a[:,::2] # 일부만 선택하는 방법

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [8]:
a[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [9]:
a[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [ ]:
a[0,2] # 팬시 인덱싱

np.int64(2)