In [1]:
import numpy as np

In [2]:
a = np.ones(5)

In [3]:
a

array([1., 1., 1., 1., 1.])

In [4]:
a.shape

(5,)

In [7]:
a.ndim # 차원

1

In [8]:
a.dtype

dtype('float64')

In [9]:
a.size

5

In [ ]:
a = np.ones(5, dtype=np.int8) # 원하는 타입으로 배열을 생성할 수 있다.

In [11]:
a.dtype

dtype('int8')

In [ ]:
b = a.astype(np.float32) # a자체기 바뀌는것은 아니다.

In [13]:
b.dtype

dtype('float32')

In [14]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [15]:
a

array([1, 1, 1, 1, 1], dtype=int8)

In [17]:
a.size #원소의개수

5

In [18]:
b = np.zeros((3,5))

In [19]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
b.size

15

In [ ]:
b.itemsize # byte

8

In [22]:
## copy

In [23]:
list_a = [1,2,3,4,5,6]

In [24]:
list_b = list_a

In [25]:
list_b = list_a.copy()

In [26]:
list_b

[1, 2, 3, 4, 5, 6]

In [27]:
list_b = np.array(list_a)

In [30]:
list_b[1] = 10000

In [31]:
list_a

[1, 2, 3, 4, 5, 6]

In [33]:
id(list_a) , id(list_b)

(4399865792, 4398161168)

In [34]:
a = np.arange(10)

In [35]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b = a

In [37]:
id(a), id(b)

(4398160592, 4398160592)

In [38]:
b[3] = 4000

In [39]:
b

array([   0,    1,    2, 4000,    4,    5,    6,    7,    8,    9])

In [40]:
a

array([   0,    1,    2, 4000,    4,    5,    6,    7,    8,    9])

In [41]:
c = a[1:4]

In [42]:
c

array([   1,    2, 4000])

In [43]:
c[1] = 10000

In [44]:
c

array([    1, 10000,  4000])

In [ ]:
a # a도 바뀜 리스트와 달리 = View

array([    0,     1, 10000,  4000,     4,     5,     6,     7,     8,
           9])

In [47]:
# view 
id(a)

4398160592

In [49]:
id(c) # 위치는 다른데 c는 a의 view

4398160400

In [50]:
id(c.base)

4398160592

In [51]:
id(a.base)

4310233760

In [52]:
d = a[1:4].copy()

In [57]:
d[0] = 1112e1

In [58]:
a

array([    0,     1, 10000,  4000,     4,     5,     6,     7,     8,
           9])

In [59]:
d

array([11120, 10000,  4000])

In [60]:
a[a>100]

array([10000,  4000])

In [71]:
a = np.random.randint(1, 5, (10,10))

In [72]:
a

array([[1, 3, 1, 4, 1, 3, 2, 2, 1, 1],
       [2, 3, 4, 2, 2, 4, 2, 4, 2, 4],
       [3, 4, 4, 4, 3, 2, 1, 1, 1, 4],
       [4, 4, 3, 3, 3, 4, 1, 2, 4, 4],
       [3, 3, 4, 2, 2, 3, 2, 4, 1, 2],
       [2, 1, 3, 1, 2, 4, 3, 2, 4, 3],
       [2, 3, 2, 3, 4, 2, 1, 4, 3, 2],
       [3, 4, 1, 2, 3, 3, 1, 4, 1, 3],
       [3, 1, 2, 3, 1, 1, 3, 4, 3, 2],
       [3, 1, 4, 1, 1, 1, 1, 4, 2, 3]])

In [77]:
a = np.random.rand(10)

In [79]:
a= np.random.rand(5,5)

In [81]:
a.shape

(5, 5)

In [82]:
np.random.randn(100,100)

array([[-0.60093743, -1.78672994,  1.26805989, ...,  0.53481198,
        -1.69864073, -0.98590698],
       [ 1.19752821,  1.25632861, -1.38538703, ..., -0.39458208,
         0.45368953, -1.74157315],
       [-0.23142428, -0.21448272, -0.12755306, ...,  0.16952135,
         0.59177434,  0.41830218],
       ...,
       [ 0.13997868, -0.4105182 ,  0.43729026, ...,  1.33109223,
        -1.1585852 , -0.37607556],
       [ 0.17088872, -1.3517118 ,  2.0230217 , ...,  0.613277  ,
        -2.38050222, -0.10492118],
       [-0.14962871, -0.33513439, -1.82338945, ...,  0.47565257,
         1.30511052,  0.39815504]])

In [83]:
a.size

25

In [85]:
a.sum()

np.float64(11.75169029711503)

In [87]:
a.mean()

np.float64(0.47006761188460117)

In [89]:
a.std() # 표준편차

np.float64(0.32188885879866536)

In [90]:
a = np.random.randint(1,45,6)

In [91]:
a.sort

<function ndarray.sort>

In [97]:
np.sort(a)[::-1]

array([40, 36, 28, 18, 17,  2])

In [98]:
sorted(a)

[np.int64(2),
 np.int64(17),
 np.int64(18),
 np.int64(28),
 np.int64(36),
 np.int64(40)]

In [99]:
np.argsort(a)

array([0, 1, 2, 3, 4, 5])

In [100]:
a

array([ 2, 17, 18, 28, 36, 40])

In [101]:
a

array([ 2, 17, 18, 28, 36, 40])

In [102]:
a

array([ 2, 17, 18, 28, 36, 40])