In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
pd.Series([1,2,6,7,np.nan])

0    1.0
1    2.0
2    6.0
3    7.0
4    NaN
dtype: float64

In [4]:
datas = pd.date_range('20250101', periods=10)

In [5]:
datas

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [8]:
df = pd.DataFrame(np.random.randn(10,4), index=datas, columns=list('ABCD'))

In [9]:
df

A         B         C         D
2025-01-01  0.699224 -0.461711 -0.234968 -1.345556
2025-01-02 -0.051214  0.643925  0.850474  0.985476
2025-01-03 -0.506754  0.233068 -1.732457  0.153569
2025-01-04  0.488234 -1.340350 -0.241041  1.073067
2025-01-05 -0.551811 -0.304831 -0.741477  1.077628
2025-01-06 -0.830621  0.689551 -0.676930  1.264728
2025-01-07  1.257720 -1.322001  1.758200 -1.170407
2025-01-08  0.705155  0.719022  0.456983  0.521585
2025-01-09 -0.438337 -0.220466 -0.658636 -1.844779
2025-01-10 -0.568419  2.654237 -0.549296 -1.280218

In [12]:
df = pd.DataFrame({'A':1.,
                   'B' : pd.Timestamp('20240101'),
                   'C' : pd.Series(1, index=(range(4)), dtype='float32')})

In [13]:
df

A          B    C
0  1.0 2024-01-01  1.0
1  1.0 2024-01-01  1.0
2  1.0 2024-01-01  1.0
3  1.0 2024-01-01  1.0

In [15]:
df.dtypes

A          float64
B    datetime64[s]
C          float32
dtype: object

In [18]:
pd.Series([1,2,6,7,np.nan]) # 시리즈 생성
df = pd.DataFrame({'A':1.,
                   'B' : pd.Timestamp('20240101'),
                   'C' : pd.Series(1, index=(range(4)), dtype='float32')}) # 데이터 프레임 생성
datas = pd.date_range('20250101', periods=10) 
df.index # 인덱스 값 보기
df.columns # 열 값 보기
df.to_numpy # numpy로 바꾸기 같은 타입으로 이루어져있어야함
df.describe() # 통계정보
df.T # 전치행렬 구하기

0                    1                    2  \
A                  1.0                  1.0                  1.0   
B  2024-01-01 00:00:00  2024-01-01 00:00:00  2024-01-01 00:00:00   
C                  1.0                  1.0                  1.0   

                     3  
A                  1.0  
B  2024-01-01 00:00:00  
C                  1.0

In [22]:
df = pd.DataFrame({'A':1.,
                   'B' : pd.Timestamp('20240101'),
                   'C' : pd.Series(1, index=(range(4)), dtype='float32')}) # 데이터 프레임 생성

In [24]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [25]:
df

A          B    C
0  1.0 2024-01-01  1.0
1  1.0 2024-01-01  1.0
2  1.0 2024-01-01  1.0
3  1.0 2024-01-01  1.0

In [26]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [3]:
s1 = pd.Series([1,2,3,4,5])

In [4]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [21]:
df = pd.DataFrame([[1,2,3,1,2,3],[4,5,6,8,9,10]])

In [22]:
df

0  1  2  3  4   5
0  1  2  3  1  2   3
1  4  5  6  8  9  10

In [11]:
df.iloc[0]

0    1
1    2
2    3
Name: 0, dtype: int64

In [12]:
df[1][1]

np.int64(5)

In [13]:
df.iloc[0][0]

np.int64(1)

In [16]:
s = pd.Series([1,2,3,4,np.nan])

In [17]:
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [20]:
df.iloc[:,0]

0    1
1    4
Name: 0, dtype: int64

In [23]:
df[0:1]

0  1  2  3  4  5
0  1  2  3  1  2  3

In [24]:
df[0]

0    1
1    4
Name: 0, dtype: int64

In [28]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index=["하나", "둘", "셋"], columns=["하나","둘","셋"])

In [29]:
ㅇf

NameError: name 'ᄋf' is not defined

In [30]:
df

하나  둘  셋
하나   1  2  3
둘    4  5  6
셋    7  8  9

In [32]:
df2 = pd.DataFrame({'A':1,'B':2,'C':pd.Series(1, index=list(range(4)))})

In [34]:
df2

A  B  C
0  1  2  1
1  1  2  1
2  1  2  1
3  1  2  1

In [35]:
df.index

Index(['하나', '둘', '셋'], dtype='object')

In [36]:
df.columns

Index(['하나', '둘', '셋'], dtype='object')

In [43]:
a = df.to_numpy()

In [44]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
df.describe()

하나    둘    셋
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0